name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['oldstable', 'stable']
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '${{ matrix.go }}'

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Test
        run: |
          go test -v --race -covermode=atomic -coverprofile=coverage.out
